In [ ]:
1. #1.
Q1. Create a DataFrame with the following student marks and display students with marks above 80.
{'Name': ['Anu', 'Raj', 'Diya', 'Kiran'], 'Marks': [76, 88, 95, 65]}

expected Output:
    
    Name  Marks
1   Raj     88
2  Diya     95

In [4]:
import pandas as pd
data= {'Name': ['Anu', 'Raj', 'Diya', 'Kiran'], 'Marks': [76, 88, 95, 65]}
dataset=pd.DataFrame(data)
dataset_above80=dataset[dataset['Marks']>80]
dataset_above80

   Name  Marks
1   Raj     88
2  Diya     95

In [ ]:
#2.Q2. Create a DataFrame and find the mean salary grouped by department.
{'Name': ['Amit', 'Sneha', 'Kunal', 'Riya'], 'Department': ['HR', 'IT', 'HR', 'IT'], 'Salary': [30000, 50000, 35000, 52000]}
Expected Output:
Department
HR    32500.0
IT    51000.0
Name: Salary, dtype: float64

In [5]:
import pandas as pd
data={'Name': ['Amit', 'Sneha', 'Kunal', 'Riya'], 'Department': ['HR', 'IT', 'HR', 'IT'], 'Salary': [30000, 50000, 35000, 52000]}
dataset=pd.DataFrame(data)
total=dataset.groupby('Department')['Salary'].mean()
total

Department
HR    32500.0
IT    51000.0
Name: Salary, dtype: float64

In [ ]:
#3.Q3. Create a DataFrame and apply label encoding to the Gender column.
{'Name': ['Arjun', 'Leela', 'Kiran'], 'Gender': ['Male', 'Female', 'Male']}
Expected Output:
    Name  Gender  Gender_encoded
0  Arjun    Male               1
1  Leela  Female               0
2  Kiran    Male               1

In [9]:
import pandas as pd
data={'Name': ['Arjun', 'Leela', 'Kiran'], 'Gender': ['Male', 'Female', 'Male']}
dataset=pd.DataFrame(data)
dataset['Gender_encoded']=pd.get_dummies(dataset['Gender'],drop_first=True)
dataset

    Name  Gender  Gender_encoded
0  Arjun    Male               1
1  Leela  Female               0
2  Kiran    Male               1

In [ ]:
#4.🔹Q4. Normalize the 'Score' column using Min-Max scaling.
{'Student': ['A', 'B', 'C'], 'Score': [55, 80, 65]}

Expected Output:
    Student  Score  Normalized_Score
0       A     55               0.0
1       B     80               1.0
2       C     65               0.4

In [12]:
import pandas as pd
data={'Student': ['A', 'B', 'C'], 'Score': [55, 80, 65]}
dataset=pd.DataFrame(data)
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
dataset['Normalized_Score']=scaler.fit_transform(dataset[['Score']])
dataset

  Student  Score  Normalized_Score
0       A     55               0.0
1       B     80               1.0
2       C     65               0.4

In [ ]:
#5.
Use SVM, RandomForest, and GaussianNB to classify customers as 'Buy' or 'Not Buy' based on Age and Salary.
{'Age': [22, 25, 47, 52, 46, 56, 23], 'Salary': [15000, 29000, 48000, 60000, 52000, 61000, 17000], 'Buy': [0, 0, 1, 1, 1, 1, 0]}

In [23]:
import pandas as pd
data = {'Age': [22, 25, 47, 52, 46, 56, 23], 'Salary': [15000, 29000, 48000, 60000, 52000, 61000, 17000], 'Buy': [0, 0, 1, 1, 1, 1, 0]}
dataset=pd.DataFrame(data)
dataset


independent=dataset[['Age','Salary']]
dependent=dataset[['Buy']]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3)

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,classification_report

#SVC
classifier=SVC(C=10)
model=classifier.fit(x_train,y_train)
y_pred=model.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
report = classification_report(y_test,y_pred)
print("SVM:")
print(cm)
print(report)

#RandomForestClassifier
classifier=RandomForestClassifier()
model=classifier.fit(x_train,y_train)
y_pred=model.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
report = classification_report(y_test,y_pred)
print("RandomForestClassifier:")
print(cm)
print(report)

#GaussianNB
classifier=GaussianNB()
model=classifier.fit(x_train,y_train)
y_pred=model.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
report = classification_report(y_test,y_pred)
print("GaussianNB:")
print(cm)
print(report)

C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\ipykernel_launcher.py:29: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

SVM:
[[1 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

RandomForestClassifier:
[[1 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

GaussianNB:
[[1 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

C:\Users\DELL\anaconda3\envs\aiml\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)